In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from geopy.geocoders import Nominatim 

import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

df = pd.read_csv('us_cities_ml_dataset.csv', sep=',')

In [2]:
country = 'United States'
city_names = df['location']

longitude =[]
latitude =[]
geolocator = Nominatim(user_agent="Trips")

for c in city_names.values:
    location = geolocator.geocode(c+','+ country)
    latitude.append(location.latitude)
    longitude.append(location.longitude)


df ['longitude'] = longitude
df ['latitude']  = latitude

In [3]:
df.head(5)

       location  longitude   latitude
0      New York -74.006015  40.712728
1        Boston -71.060511  42.355433
2  Philadelphia -75.163526  39.952724
3    Pittsburgh -79.990086  40.441694
4       Buffalo -78.878392  42.886717

In [4]:
l2 = df.iloc[:,1:3:1]
l2

     longitude   latitude
0   -74.006015  40.712728
1   -71.060511  42.355433
2   -75.163526  39.952724
3   -79.990086  40.441694
4   -78.878392  42.886717
5   -74.172367  40.735657
6   -72.690855  41.764582
7   -71.412834  41.823989
8   -70.258491  43.663471
9   -73.754968  42.651167
10  -80.193620  25.774173
11  -81.379030  28.542111
12  -84.389815  33.754466
13  -80.843083  35.227209
14  -86.774298  36.162277
15  -90.073026  29.955914
16  -82.458444  27.947760
17  -86.802433  33.520682
18  -77.434280  37.538509
19  -85.759407  38.254238
20  -87.624421  41.875562
21  -81.693677  41.499657
22  -83.046640  42.331551
23  -93.265469  44.977300
24  -90.191015  38.628028
25  -86.158350  39.768333
26  -87.909075  43.038648
27  -83.000707  39.962260
28  -94.578142  39.100105
29  -95.938376  41.258746
30  -96.796856  32.776272
31  -95.367697  29.758938
32  -97.743700  30.271129
33  -98.495141  29.424600
34 -106.487040  31.760116
35 -106.650985  35.084103
36  -97.517054  35.472989
37  -95.992752  36.156312
38 -112.074141  33.448437
39 -110.974847  32.222876
40 -118.242766  34.053691
41 -122.419329  37.779259
42 -117.162772  32.717420
43 -122.330062  47.603832
44 -122.674194  45.520247
45 -115.148413  36.167426
46 -121.493895  38.581061
47 -111.886797  40.759620
48 -104.984862  39.739236
49 -116.200886  43.616616

In [5]:
kmeans = KMeans(5)
kmeans.fit(l2)

identified_clusters = kmeans.fit_predict(l2)
identified_clusters = list(identified_clusters)
df['loc_clusters']  = identified_clusters

In [6]:
df

          location   longitude   latitude  loc_clusters
0         New York  -74.006015  40.712728             1
1           Boston  -71.060511  42.355433             1
2     Philadelphia  -75.163526  39.952724             1
3       Pittsburgh  -79.990086  40.441694             4
4          Buffalo  -78.878392  42.886717             1
5           Newark  -74.172367  40.735657             1
6         Hartford  -72.690855  41.764582             1
7       Providence  -71.412834  41.823989             1
8    Portland (ME)  -70.258491  43.663471             1
9           Albany  -73.754968  42.651167             1
10           Miami  -80.193620  25.774173             3
11         Orlando  -81.379030  28.542111             3
12         Atlanta  -84.389815  33.754466             3
13       Charlotte  -80.843083  35.227209             3
14       Nashville  -86.774298  36.162277             4
15     New Orleans  -90.073026  29.955914             3
16           Tampa  -82.458444  27.947760             3
17      Birmingham  -86.802433  33.520682             3
18        Richmond  -77.434280  37.538509             1
19      Louisville  -85.759407  38.254238             4
20         Chicago  -87.624421  41.875562             4
21       Cleveland  -81.693677  41.499657             4
22         Detroit  -83.046640  42.331551             4
23     Minneapolis  -93.265469  44.977300             4
24       St. Louis  -90.191015  38.628028             4
25    Indianapolis  -86.158350  39.768333             4
26       Milwaukee  -87.909075  43.038648             4
27        Columbus  -83.000707  39.962260             4
28     Kansas City  -94.578142  39.100105             0
29           Omaha  -95.938376  41.258746             0
30          Dallas  -96.796856  32.776272             0
31         Houston  -95.367697  29.758938             0
32          Austin  -97.743700  30.271129             0
33     San Antonio  -98.495141  29.424600             0
34         El Paso -106.487040  31.760116             0
35     Albuquerque -106.650985  35.084103             0
36   Oklahoma City  -97.517054  35.472989             0
37           Tulsa  -95.992752  36.156312             0
38         Phoenix -112.074141  33.448437             2
39          Tucson -110.974847  32.222876             2
40     Los Angeles -118.242766  34.053691             2
41   San Francisco -122.419329  37.779259             2
42       San Diego -117.162772  32.717420             2
43         Seattle -122.330062  47.603832             2
44   Portland (OR) -122.674194  45.520247             2
45       Las Vegas -115.148413  36.167426             2
46      Sacramento -121.493895  38.581061             2
47  Salt Lake City -111.886797  40.759620             2
48          Denver -104.984862  39.739236             0
49           Boise -116.200886  43.616616             2

In [7]:
input_city = input("Enter a city name: ")
print("input : ",input_city,'\n')
cluster = df.loc[df['location'] == input_city, 'loc_clusters']
cluster = cluster.iloc[0]
cluster
cities = df.loc[df['loc_clusters'] == cluster, 'location']
cities
for c in range(len(cities)):
    if cities.iloc[c] == input_city:
        continue
    else:
        print(cities.iloc[c])

input :  New York

Boston
Philadelphia
Buffalo
Newark
Hartford
Providence
Portland (ME)
Albany
Richmond