In [1]:
import pandas as pd
df = pd.read_csv("AG_News/test.csv")
df.head(5)

,Class Index,Title,Description
0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...
1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o..."
2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...
3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...
4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...

In [2]:
class_map = {}

with open("AG_News/classes_name.txt", "r", encoding="utf-8") as f:
    for line in f:
        idx, label = line.strip().split(" ", 1)
        class_map[int(idx)] = label

print("Class mapping:", class_map)

Class mapping: {1: 'World', 2: 'Sports', 3: 'Business', 4: 'Sci/Tech'}

In [6]:
df["Class_Name"] = df["Class Index"].map(class_map)
df.head(5)

,Class Index,Title,Description,Class_Name
0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...,Business
1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o...",Sci/Tech
2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...,Sci/Tech
3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...,Sci/Tech
4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...,Sci/Tech